{{- if and (not .Values.auth.existingSecret) .Values.auth.apiKey -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bindery.fullname" . }}-auth
  labels:
    {{- include "bindery.labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
stringData:
  {{ .Values.auth.apiKeySecretKey }}: {{ .Values.auth.apiKey | quote }}
{{- end }}
