{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "bindery.serviceAccountName" . }}
  labels:
    {{- include "bindery.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
