package dnb

import (
	"context"
	"os"
	"strings"
	"testing"
	"time"
)

// randomSampleISBNs is a deterministic sample of 50 ISBNs drawn from
// broad DNB SRU queries (mixed years 2022-2025, audio carriers,
// German-language novels, specific popular authors). The sample was
// generated by spreading across 8 distinct queries and randomly
// selecting from the union — see the script in the issue thread.
//
// Unlike TestLive_DNB_AllZippokingISBNs (which is a curated regression
// guard for the specific cases zippoking reported), this list is meant
// as a *broad-coverage probe* to surface failure modes our curated set
// would miss. Failures here are interesting — they reveal gaps in our
// fallback hierarchy that real users would hit but we didn't anticipate.
var randomSampleISBNs = []string{
	"978-3-8449-4463-1", "978-3-10-492287-4", "978-1-66808-779-4", "978-3-98660-192-8",
	"978-3-552-07567-2", "978-3-499-01899-2", "978-3-499-01717-9", "978-3-257-80463-8",
	"978-91-0-080428-2", "978-3-06-123376-1", "978-3-910610-38-5", "978-617-522-269-0",
	"978-3-7597-7162-9", "978-3-06-123317-4", "978-3-8301-9417-0", "978-3-7546-0448-9",
	"978-2-330-20134-0", "978-952-388-360-4", "978-3-98718-144-3", "978-3-499-01345-4",
	"978-3-499-01897-8", "978-3-7590-2005-5", "978-3-8398-2237-1", "978-3-96188-190-1",
	"978-3-7598-6561-8", "978-3-498-00748-5", "978-3-98695-190-0", "978-3-7545-2254-7",
	"978-628-96727-5-6", "978-3-7562-9370-4", "978-3-96753-199-2", "978-89-374-2285-0",
	"978-1-5294-3511-5", "978-3-406-79553-4", "978-3-96753-192-3", "978-3-644-02587-5",
	"978-3-8321-6724-0", "978-3-328-11136-8", "978-3-949101-05-2", "978-3-7598-6562-5",
	"978-3-98910-249-1", "978-3-95510-356-9", "978-3-7324-8419-5", "978-3-06-123375-4",
	"978-3-68946-165-2", "978-3-7693-7992-1", "978-3-462-00406-9", "978-3-641-31480-4",
	"978-3-257-02170-7", "978-3-7518-8040-4",
}

// TestLive_DNB_AllZippokingISBNs is the on-demand proof test for issue
// #667. It hits the real DNB SRU endpoint for every ISBN zippoking
// reported across #284, #608, and #667 — fifteen titles spanning four
// years of complaints. For each:
//
//   - The record must come back.
//   - Title must be non-empty AND must NOT contain MARC non-sorting
//     bracket control chars (U+0098 / U+009C). This is the
//     "Der/Die/Das renders as garbage" bug in #667.
//   - Author must be present with non-empty Name. This catches the
//     "100 missing, 700 only" case in translated/audio editions.
//
// Output on success is one line per ISBN, suitable for pasting into the
// issue thread as proof. Run with: BINDERY_LIVE=1 go test
// ./internal/metadata/dnb -run TestLive -v -count=1
//
// Skipped by default (network-dependent, polite to DNB). The nightly
// workflow at .github/workflows/live-dnb.yml (to be added in PR2) sets
// BINDERY_LIVE=1 and runs this on a schedule.
func TestLive_DNB_AllZippokingISBNs(t *testing.T) {
	if os.Getenv("BINDERY_LIVE") == "" {
		t.Skip("set BINDERY_LIVE=1 to hit live DNB SRU")
	}

	isbns := []struct {
		isbn   string
		source string // origin of this case
		note   string // what code path it exercises
	}{
		// --- zippoking's reports (issue #667 must pass all of these) -----
		// From #284 — were marked fixed; regression guard.
		{"978-3-458-68436-7", "#284", "regression: was marked fixed"},
		{"978-3-7432-2240-3", "#284", "regression: was marked fixed"},
		{"978-3-7599-0048-7", "#284", "regression: was marked fixed"},

		// From #608 / #667 — the twelve zippoking explicitly demanded.
		{"978-3-8373-9555-6", "#608", "DNB record with synthetic author slug"},
		{"978-87-27-26711-1", "#608", "non-German ISBN range, German edition"},
		{"978-3-8449-4284-2", "#608", "translated Norwegian work, 700-aut path"},
		{"978-3-7324-7563-6", "#608", "audiobook ('Ungekürzte Lesung')"},
		{"978-3-96092-698-6", "#608", "non-fiction"},
		{"978-3-8371-6512-8", "#608", "Grisham translation, 100-gnd path"},
		{"978-3-8449-3577-6", "#608", "Der/Die/Das NSB/NSE wrap (Juli Zeh)"},
		{"978-3-9597-2586-6", "#608", "non-fiction Hill, 100-gnd path"},
		{"978-3-86717-354-4", "#608", "Harry Potter audiobook, ctb-only fallback"},
		{"978-3-8371-5566-2", "#608", "Der Astronaut (NSB/NSE wrap)"},
		{"978-3-8449-0704-9", "#608", "Marc-Uwe Kling, 100-gnd path"},
		{"978-3-8449-4504-1", "#608", "Pelicot autobiography, 700-aut path"},

		// --- Extension set: diverse audiobooks and German bestsellers ---
		// Selected to exercise distinct code paths.
		{"978-3-7599-0385-3", "extension", "Charlotte Link 'Die Betrogene' (NSB/NSE)"},
		{"978-3-7341-1629-2", "extension", "Charlotte Link 'Die Rosenzüchterin' (NSB/NSE)"},
		{"978-3-7545-2254-7", "extension", "'Das Antike Drama' Aischylos audiobook (NSB/NSE, ancient author)"},
		{"978-3-7540-2471-3", "extension", "modern romance audiobook (3 novels)"},
		{"978-3-8398-2237-1", "extension", "Andreas Winkelmann thriller audiobook (narrator-prefixed title)"},
		{"978-3-8449-4463-1", "extension", "English-origin audiobook in German edition"},
		{"978-3-8288-4978-5", "extension", "academic work on Walter Moers / Zamonien"},
		{"978-3-949840-48-7", "extension", "Erich Kästner classic audiobook (multi-work compilation)"},
		{"978-3-98695-190-0", "extension", "devotional audiobook with no 100 entry"},
		{"978-3-86678-807-7", "extension", "Cornelia Funke biographical (Tintenherz era)"},
	}

	c := New()
	// Generous per-ISBN deadline so one slow upstream doesn't kill the run.
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Minute)
	defer cancel()

	t.Logf("=== Live DNB add-by-ISBN verification for issue #667 ===")
	t.Logf("Endpoint: %s", sruBase)
	var failures []string
	for _, tc := range isbns {
		tc := tc
		t.Run(tc.isbn, func(t *testing.T) {
			book, err := c.GetBookByISBN(ctx, tc.isbn)
			if err != nil {
				failures = append(failures, tc.isbn)
				t.Fatalf("[%s] GetBookByISBN: %v", tc.source, err)
			}
			if book == nil {
				failures = append(failures, tc.isbn)
				t.Fatalf("[%s] no DNB record for ISBN", tc.source)
			}
			if book.Title == "" {
				failures = append(failures, tc.isbn)
				t.Fatalf("[%s] empty title in record %s", tc.source, book.ForeignID)
			}
			if strings.ContainsRune(book.Title, '') || strings.ContainsRune(book.Title, '') {
				failures = append(failures, tc.isbn)
				t.Fatalf("[%s] title %q still contains MARC NSB/NSE control characters", tc.source, book.Title)
			}
			if book.Author == nil {
				failures = append(failures, tc.isbn)
				t.Fatalf("[%s] no author in record %s (title %q) — 700 fallback may need extending", tc.source, book.ForeignID, book.Title)
			}
			if book.Author.Name == "" {
				failures = append(failures, tc.isbn)
				t.Fatalf("[%s] empty author name in record %s", tc.source, book.ForeignID)
			}

			t.Logf("OK [%s] %s → %q by %s (foreignId=%s, author=%s) — %s",
				tc.source, tc.isbn, book.Title, book.Author.Name,
				book.ForeignID, book.Author.ForeignID, tc.note)
		})
	}

	if len(failures) > 0 {
		t.Logf("=== FAILURES (%d/%d) === %v", len(failures), len(isbns), failures)
	} else {
		t.Logf("=== ALL %d ISBNs RESOLVE CLEANLY ===", len(isbns))
	}
}

// TestLive_DNB_RandomSample is a broad-coverage probe against 50
// pseudo-random ISBNs drawn from diverse DNB SRU queries. Unlike the
// zippoking regression set above (curated cases that MUST pass), this
// one is exploratory: it surfaces failure modes the curated set misses.
//
// Categorises results into pass / soft-fail (no record at DNB — outside
// our control) / hard-fail (record exists but extraction is wrong).
// Hard-fails are the only ones that block PR1. Soft-fails are logged
// for visibility — they reveal cases where the AddBook flow's OL/
// Hardcover fallback would have to kick in.
func TestLive_DNB_RandomSample(t *testing.T) {
	if os.Getenv("BINDERY_LIVE") == "" {
		t.Skip("set BINDERY_LIVE=1 to hit live DNB SRU")
	}

	c := New()
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Minute)
	defer cancel()

	var (
		pass     []string
		noRecord []string
		noAuthor []string
		badTitle []string
		errs     []string
	)
	for _, isbn := range randomSampleISBNs {
		isbn := isbn
		t.Run(isbn, func(t *testing.T) {
			book, err := c.GetBookByISBN(ctx, isbn)
			if err != nil {
				errs = append(errs, isbn)
				t.Errorf("error: %v", err)
				return
			}
			if book == nil {
				noRecord = append(noRecord, isbn)
				t.Logf("SOFT-FAIL: no DNB record (AddBook would fall back to OL/Hardcover)")
				return
			}
			if strings.ContainsRune(book.Title, '') || strings.ContainsRune(book.Title, '') {
				badTitle = append(badTitle, isbn)
				t.Errorf("HARD-FAIL: NSB/NSE leaked into title %q", book.Title)
				return
			}
			if book.Author == nil || book.Author.Name == "" {
				noAuthor = append(noAuthor, isbn)
				t.Logf("SOFT-FAIL: record %s (title %q) has no derivable author — extractAuthor 3-tier fallback exhausted; AddBook would use resolveAuthorForBook ISBN cross-lookup",
					book.ForeignID, book.Title)
				return
			}
			pass = append(pass, isbn)
			t.Logf("OK: %s by %s (foreignId=%s, author=%s)",
				book.Title, book.Author.Name, book.ForeignID, book.Author.ForeignID)
		})
	}

	total := len(randomSampleISBNs)
	t.Logf("=== Random-sample probe: %d total ===", total)
	t.Logf("  PASS                : %d (%.0f%%)", len(pass), 100*float64(len(pass))/float64(total))
	t.Logf("  SOFT-FAIL no record : %d (DNB just doesn't have this ISBN)", len(noRecord))
	t.Logf("  SOFT-FAIL no author : %d (record exists but author un-extractable; OL fallback would run)", len(noAuthor))
	t.Logf("  HARD-FAIL bad title : %d (NSB/NSE leaked — must be zero)", len(badTitle))
	t.Logf("  ERROR               : %d (transport/parse failures)", len(errs))

	// Only hard-fails block the build; soft-fails are an honest accounting.
	if len(badTitle) > 0 || len(errs) > 0 {
		t.Fatalf("hard failures: %d bad titles, %d errors", len(badTitle), len(errs))
	}
}
