package nzbfetch

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"net/http"
	"net/url"
	"strings"
	"testing"
)

// endedAt fakes the final request of a fetch chain — the URL the redirects
// actually landed on (what resp.Request holds after client.Do). Responses are
// built as literals at each call site: a helper returning *http.Response
// trips bodyclose even though these fabricated responses have no body.
func endedAt(t *testing.T, finalURL string) *http.Request {
	t.Helper()
	u, err := url.Parse(finalURL)
	if err != nil {
		t.Fatalf("parse %q: %v", finalURL, err)
	}
	return &http.Request{URL: u}
}

const nzbfinder203 = `<?xml version="1.0" encoding="UTF-8"?>
<error code="203" description="This application is not allowed to download NZBs from NZBFinder."/>`

func TestError_ParsesNewznabErrorDocument(t *testing.T) {
	err := Error("https://indexer.example.com/getnzb?id=1", &http.Response{StatusCode: 400, Request: endedAt(t, "https://indexer.example.com/getnzb?id=1")}, []byte(nzbfinder203))

	msg := err.Error()
	for _, want := range []string{"fetch nzb:", "newznab error 203", "not allowed to download NZBs", "HTTP 400"} {
		if !strings.Contains(msg, want) {
			t.Errorf("error missing %q: %s", want, msg)
		}
	}
	// Same host end to end — no redirect guidance.
	if strings.Contains(msg, "redirected") {
		t.Errorf("no cross-host hop happened, but error mentions a redirect: %s", msg)
	}
}

// The #1404 shape: the release's nzbUrl points at Prowlarr, Prowlarr 302s to
// the indexer (its per-indexer Redirect setting), the indexer rejects
// Bindery's identity. The error must name both hosts and explain that the fix
// is indexer-side whitelisting — Prowlarr can't proxy Usenet grabs (#1424).
func TestError_CrossHostRedirectAddsProwlarrGuidance(t *testing.T) {
	err := Error("http://prowlarr:9696/3/download?apikey=k&link=abc", &http.Response{StatusCode: 400, Request: endedAt(t, "https://nzbfinder.ws/getnzb/abc")}, []byte(nzbfinder203))

	msg := err.Error()
	for _, want := range []string{"newznab error 203", `redirected from "prowlarr" to "nzbfinder.ws"`, "approved applications", "No Prowlarr setting avoids this hop"} {
		if !strings.Contains(msg, want) {
			t.Errorf("error missing %q: %s", want, msg)
		}
	}
}

func TestError_SameHostDifferentPortIsNotAHop(t *testing.T) {
	err := Error("http://indexer.example.com:8080/getnzb", &http.Response{StatusCode: 502, Request: endedAt(t, "https://indexer.example.com/getnzb")}, []byte("bad gateway"))
	if msg := err.Error(); strings.Contains(msg, "redirected") {
		t.Errorf("scheme/port rewrite on the same host must not read as a hand-off: %s", msg)
	}
}

func TestError_NonXMLBodyFallsBackToRawSnippet(t *testing.T) {
	err := Error("https://indexer.example.com/getnzb", &http.Response{StatusCode: 503, Request: endedAt(t, "https://indexer.example.com/getnzb")}, []byte("  <html>overloaded</html>  "))
	msg := err.Error()
	if !strings.Contains(msg, "indexer returned HTTP 503: <html>overloaded</html>") {
		t.Errorf("raw fallback wrong: %s", msg)
	}
}

func TestError_RawSnippetIsCapped(t *testing.T) {
	err := Error("https://indexer.example.com/getnzb", &http.Response{StatusCode: 500, Request: endedAt(t, "https://indexer.example.com/getnzb")}, []byte(strings.Repeat("x", MaxErrorBody)))
	if msg := err.Error(); len(msg) > rawBodyCap+200 {
		t.Errorf("raw body not capped, error is %d bytes", len(msg))
	}
}

func TestError_NilFinalRequestIsSafe(t *testing.T) {
	// Defensive: a response with no Request must not panic or emit hop text.
	err := Error("https://indexer.example.com/getnzb", &http.Response{StatusCode: 404}, []byte("not found"))
	if msg := err.Error(); strings.Contains(msg, "redirected") {
		t.Errorf("unexpected redirect text: %s", msg)
	}
}

// realNZB is the shape every indexer returns on success: an XML declaration,
// the newzBin DOCTYPE, and an <nzb> root.
const realNZB = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE nzb PUBLIC "-//newzBin//DTD NZB 1.1//EN" "http://www.newzbin.com/DTD/nzb/nzb-1.1.dtd">
<!-- generated by the indexer -->
<nzb xmlns="http://www.newzbin.com/DTD/2003/nzb">
<head><meta type="category">Audio &gt; Audiobook - DE</meta></head>
</nzb>`

// plainTextErrorBody is the #2105 shape: three prolog-legal lines followed by
// plain text on line 4. Served with HTTP 200, it reaches SAB, which reports
// `xml.etree.ElementTree.ParseError: syntax error: line 4, column 0` — an
// error that names SAB for a response the indexer got wrong.
const plainTextErrorBody = "\n\n\nYou have reached your download limit for today.\n"

func TestValidateNZB_AcceptsNZBDocument(t *testing.T) {
	err := ValidateNZB("https://indexer.example.com/getnzb?id=1",
		&http.Response{StatusCode: 200, Request: endedAt(t, "https://indexer.example.com/getnzb?id=1")},
		[]byte(realNZB))
	if err != nil {
		t.Fatalf("a real NZB must be accepted, got: %v", err)
	}
}

// A UTF-8 BOM in front of the declaration is legal and some indexers emit one.
// Rejecting it would turn a working grab into a hard failure.
func TestValidateNZB_AcceptsNZBWithUTF8BOM(t *testing.T) {
	body := append([]byte("\xef\xbb\xbf"), []byte(realNZB)...)
	err := ValidateNZB("https://indexer.example.com/getnzb",
		&http.Response{StatusCode: 200, Request: endedAt(t, "https://indexer.example.com/getnzb")},
		body)
	if err != nil {
		t.Fatalf("a BOM-prefixed NZB must be accepted, got: %v", err)
	}
}

// A non-UTF-8 declared encoding must not read as "not an NZB" either: only the
// root element name decides, and that is ASCII in every encoding an indexer
// plausibly uses.
func TestValidateNZB_AcceptsNZBWithNonUTF8Declaration(t *testing.T) {
	body := []byte(`<?xml version="1.0" encoding="ISO-8859-1"?>` + "\n" + `<nzb xmlns="http://www.newzbin.com/DTD/2003/nzb"></nzb>`)
	err := ValidateNZB("https://indexer.example.com/getnzb",
		&http.Response{StatusCode: 200, Request: endedAt(t, "https://indexer.example.com/getnzb")},
		body)
	if err != nil {
		t.Fatalf("an ISO-8859-1 NZB must be accepted, got: %v", err)
	}
}

func TestValidateNZB_RejectsPlainTextBody(t *testing.T) {
	err := ValidateNZB("https://indexer.example.com/getnzb",
		&http.Response{StatusCode: 200, Request: endedAt(t, "https://indexer.example.com/getnzb")},
		[]byte(plainTextErrorBody))
	if err == nil {
		t.Fatal("a plain-text body must be rejected before it reaches the download client")
	}
	msg := err.Error()
	for _, want := range []string{"fetch nzb:", "not an NZB", "HTTP 200", "reached your download limit"} {
		if !strings.Contains(msg, want) {
			t.Errorf("error missing %q: %s", want, msg)
		}
	}
}

// An HTML error page parses as XML far enough to yield a root element, so the
// check has to look at the root's name rather than merely "does it parse".
func TestValidateNZB_RejectsHTMLPage(t *testing.T) {
	err := ValidateNZB("https://indexer.example.com/getnzb",
		&http.Response{StatusCode: 200, Request: endedAt(t, "https://indexer.example.com/getnzb")},
		[]byte("<html>\n<body>Service temporarily unavailable</body>\n</html>"))
	if err == nil {
		t.Fatal("an HTML page must be rejected")
	}
	if msg := err.Error(); !strings.Contains(msg, "not an NZB") {
		t.Errorf("error should say the body is not an NZB: %s", msg)
	}
}

// Some indexers answer a refused grab with a newznab error document and HTTP
// 200 rather than a 4xx, which skips Error() entirely. The structured detail
// must survive that route too.
func TestValidateNZB_ReportsNewznabErrorServedWith200(t *testing.T) {
	err := ValidateNZB("https://indexer.example.com/getnzb",
		&http.Response{StatusCode: 200, Request: endedAt(t, "https://indexer.example.com/getnzb")},
		[]byte(nzbfinder203))
	if err == nil {
		t.Fatal("a newznab error document must be rejected")
	}
	msg := err.Error()
	for _, want := range []string{"newznab error 203", "not allowed to download NZBs"} {
		if !strings.Contains(msg, want) {
			t.Errorf("error missing %q: %s", want, msg)
		}
	}
}

// The #1404 hop guidance applies to a bad 200 exactly as it does to a 4xx: the
// redirect is what put Bindery in front of the indexer in the first place.
func TestValidateNZB_CrossHostRedirectAddsProwlarrGuidance(t *testing.T) {
	err := ValidateNZB("http://prowlarr:9696/2/download?apikey=k&link=abc",
		&http.Response{StatusCode: 200, Request: endedAt(t, "https://files.indexer.example.com/getnzb/abc")},
		[]byte(plainTextErrorBody))
	if err == nil {
		t.Fatal("expected rejection")
	}
	if msg := err.Error(); !strings.Contains(msg, `redirected from "prowlarr" to "files.indexer.example.com"`) {
		t.Errorf("error missing redirect hop: %s", msg)
	}
}

func TestValidateNZB_RejectsEmptyBody(t *testing.T) {
	err := ValidateNZB("https://indexer.example.com/getnzb",
		&http.Response{StatusCode: 200, Request: endedAt(t, "https://indexer.example.com/getnzb")},
		nil)
	if err == nil {
		t.Fatal("an empty body must be rejected")
	}
}

func TestValidateNZB_SnippetIsCapped(t *testing.T) {
	err := ValidateNZB("https://indexer.example.com/getnzb",
		&http.Response{StatusCode: 200, Request: endedAt(t, "https://indexer.example.com/getnzb")},
		[]byte(strings.Repeat("x", 64<<10)))
	if err == nil {
		t.Fatal("expected rejection")
	}
	if msg := err.Error(); len(msg) > rawBodyCap+200 {
		t.Errorf("snippet not capped, error is %d bytes", len(msg))
	}
}

// bzip2NZB is a bzip2-compressed minimal NZB. Go's stdlib decompresses bzip2
// but cannot produce it, so the fixture is embedded rather than built here.
const bzip2NZB = "QlpoMTFBWSZTWYGv0DkAAA/fgAAQUAP4V4UABgA+593QIABoRTagAxDZQGnpAAaoZGhgRoAAaaeo" +
	"yN+FNosEHLTy84GaiI23SCfBABtTrNAysBurFOfLAEAu7kQ8Hf1AYxLXW6hJCM1jjeqUIg5IaRnv" +
	"gKkaHpkn/F3JFOFCQga/QOQ="

func gzipped(t *testing.T, payload string) []byte {
	t.Helper()
	var buf bytes.Buffer
	zw := gzip.NewWriter(&buf)
	if _, err := zw.Write([]byte(payload)); err != nil {
		t.Fatalf("gzip write: %v", err)
	}
	if err := zw.Close(); err != nil {
		t.Fatalf("gzip close: %v", err)
	}
	return buf.Bytes()
}

// Some newznab indexers serve the NZB as a gzip *file* — Content-Type
// application/x-gzip with no Content-Encoding — which the HTTP transport does
// not unwrap. Both download clients sniff the magic and decompress it
// themselves (SABnzbd's process_single_nzb: "Supports NZB, NZB.BZ2, NZB.GZ and
// GZ.NZB-in-disguise"), so rejecting those bytes would break a grab that works
// today. That is a worse outcome than the bug this validation fixes.
func TestValidateNZB_AcceptsGzippedNZB(t *testing.T) {
	err := ValidateNZB("https://indexer.example.com/getnzb",
		&http.Response{StatusCode: 200, Request: endedAt(t, "https://indexer.example.com/getnzb")}, gzipped(t, realNZB))
	if err != nil {
		t.Fatalf("a gzipped NZB must be accepted, got: %v", err)
	}
}

// Same argument as gzip: SAB names NZB.BZ2 in the formats it accepts, so a
// bzip2 body must not be rejected either.
func TestValidateNZB_AcceptsBzip2NZB(t *testing.T) {
	body, err := base64.StdEncoding.DecodeString(bzip2NZB)
	if err != nil {
		t.Fatalf("decode fixture: %v", err)
	}
	if err := ValidateNZB("https://indexer.example.com/getnzb",
		&http.Response{StatusCode: 200, Request: endedAt(t, "https://indexer.example.com/getnzb")}, body); err != nil {
		t.Fatalf("a bzip2 NZB must be accepted, got: %v", err)
	}
}

// Unwrapping the archive must not become a blanket "compressed means valid":
// the point of the check is the content, and a compressed error page is still
// an error page.
func TestValidateNZB_RejectsGzippedErrorPage(t *testing.T) {
	err := ValidateNZB("https://indexer.example.com/getnzb",
		&http.Response{StatusCode: 200, Request: endedAt(t, "https://indexer.example.com/getnzb")},
		gzipped(t, "You have reached your download limit for today."))
	if err == nil {
		t.Fatal("a gzipped error page must be rejected")
	}
	if msg := err.Error(); !strings.Contains(msg, "reached your download limit") {
		t.Errorf("error should quote the decompressed body: %s", msg)
	}
}

// A body that claims to be an archive and isn't must not have its raw bytes
// dumped into the error message — that is unreadable in a log and in the
// download row.
func TestValidateNZB_RejectsCorruptCompressedBody(t *testing.T) {
	body := append([]byte{0x1f, 0x8b}, []byte{0x00, 0xff, 0xfe, 0x01, 0x02}...)
	err := ValidateNZB("https://indexer.example.com/getnzb",
		&http.Response{StatusCode: 200, Request: endedAt(t, "https://indexer.example.com/getnzb")}, body)
	if err == nil {
		t.Fatal("a corrupt archive must be rejected")
	}
	msg := err.Error()
	if !strings.Contains(msg, "could not be decompressed") {
		t.Errorf("error should name the decompression failure: %s", msg)
	}
	if strings.ContainsRune(msg, '\xfe') {
		t.Errorf("raw archive bytes must not reach the message: %q", msg)
	}
}

// Expanding a compressed body to find the root element must be bounded, or a
// decompression bomb turns a validation check into an allocation attack.
func TestValidateNZB_DecompressionIsBounded(t *testing.T) {
	err := ValidateNZB("https://indexer.example.com/getnzb",
		&http.Response{StatusCode: 200, Request: endedAt(t, "https://indexer.example.com/getnzb")},
		gzipped(t, strings.Repeat("a", 256<<20)))
	if err == nil {
		t.Fatal("a body with no NZB root must be rejected however large it expands")
	}
}

// An empty 200 used to render as "…is not an NZB: " with nothing after the
// colon, which reads like the message itself was truncated.
func TestValidateNZB_EmptyBodyHasItsOwnMessage(t *testing.T) {
	err := ValidateNZB("https://indexer.example.com/getnzb",
		&http.Response{StatusCode: 200, Request: endedAt(t, "https://indexer.example.com/getnzb")}, nil)
	if err == nil {
		t.Fatal("an empty body must be rejected")
	}
	msg := err.Error()
	if !strings.Contains(msg, "empty body") {
		t.Errorf("empty body needs its own phrasing, got: %s", msg)
	}
	if strings.HasSuffix(msg, ": ") || strings.Contains(msg, "is not an NZB: ") {
		t.Errorf("message must not trail off after a colon: %q", msg)
	}
}
